# # FROM node:20-alpine

# # # ---------- FRONTEND ----------
# # WORKDIR /frontend
# # COPY package*.json ./
# # RUN npm install
# # COPY . .

# # EXPOSE 5173
# # CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


# # Stage 1: Build the application
# FROM node:20-alpine AS builder
# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .
# RUN npm run build

# # Stage 2: Runtime (serve static dist)
# FROM node:20-alpine
# WORKDIR /app

# RUN npm install -g serve

# COPY --from=builder /app/dist ./dist

# EXPOSE 5173

# CMD ["serve", "-s", "dist", "-l", "5173"]





# ---------- Build stage ----------
FROM node:20-alpine AS builder

WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---------- Runtime stage ----------
FROM node:20-alpine

WORKDIR /frontend

RUN npm install -g serve

COPY --from=builder /frontend/dist ./dist

EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]